import JSZip from 'jszip'
import { Site, PROVIDERS } from './types'

function statusColor(site: Site): string {
  switch (site.status) {
    case 'completed': return 'ff00aa00'
    case 'in_progress': return 'ff0055ff'
    case 'blocked': return 'ff0000ff'
    default: return 'ffaaaaaa'
  }
}

function buildKML(sites: Site[]): string {
  const placemarks = sites
    .filter(s => s.lat && s.lng)
    .map(site => {
      const diaInfo = PROVIDERS.map(p => {
        const d = site.dias[p]
        if (!d) return `${p}: Not requested`
        return `${p}: ${d.status}${d.circuitNumber ? ` (${d.circuitNumber})` : ''}`
      }).join('&#10;')

      return `
    <Placemark>
      <name>${site.name}</name>
      <description><![CDATA[
        <b>Address:</b> ${site.address}, ${site.city} - ${site.state}<br/>
        <b>Status:</b> ${site.status}<br/>
        <br/><b>DIA Circuits:</b><br/>
        ${PROVIDERS.map(p => {
          const d = site.dias[p]
          return `${p}: ${d ? d.status + (d.circuitNumber ? ` — ${d.circuitNumber}` : '') : 'Not requested'}`
        }).join('<br/>')}
        ${site.notes ? `<br/><br/><b>Notes:</b> ${site.notes}` : ''}
        ${site.aiDescription ? `<br/><br/><b>AI Site Analysis:</b><br/>${site.aiDescription}` : ''}
      ]]></description>
      <Style>
        <IconStyle>
          <color>${statusColor(site)}</color>
          <scale>1.2</scale>
          <Icon><href>http://maps.google.com/mapfiles/kml/paddle/wht-circle.png</href></Icon>
        </IconStyle>
      </Style>
      <Point>
        <coordinates>${site.lng},${site.lat},0</coordinates>
      </Point>
    </Placemark>`
    }).join('\n')

  return `<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>Telecom Rollout Sites</name>
    <description>Generated by Telecom Rollout PM</description>
    ${placemarks}
  </Document>
</kml>`
}

export async function generateKMZ(sites: Site[], filename = 'rollout_sites'): Promise<Blob> {
  const zip = new JSZip()
  const kml = buildKML(sites)
  zip.file('doc.kml', kml)
  const blob = await zip.generateAsync({ type: 'blob', compression: 'DEFLATE' })
  return blob
}

export function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}
